// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: memory/memory.proto

package memory

import (
	common "agent-platform/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 记忆类型
type MemoryType int32

const (
	MemoryType_MEMORY_TYPE_UNSPECIFIED MemoryType = 0
	MemoryType_MEMORY_TYPE_IMPORTANT   MemoryType = 1
	MemoryType_MEMORY_TYPE_SUMMARY     MemoryType = 2
	MemoryType_MEMORY_TYPE_FACT        MemoryType = 3
)

// Enum value maps for MemoryType.
var (
	MemoryType_name = map[int32]string{
		0: "MEMORY_TYPE_UNSPECIFIED",
		1: "MEMORY_TYPE_IMPORTANT",
		2: "MEMORY_TYPE_SUMMARY",
		3: "MEMORY_TYPE_FACT",
	}
	MemoryType_value = map[string]int32{
		"MEMORY_TYPE_UNSPECIFIED": 0,
		"MEMORY_TYPE_IMPORTANT":   1,
		"MEMORY_TYPE_SUMMARY":     2,
		"MEMORY_TYPE_FACT":        3,
	}
)

func (x MemoryType) Enum() *MemoryType {
	p := new(MemoryType)
	*p = x
	return p
}

func (x MemoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_memory_memory_proto_enumTypes[0].Descriptor()
}

func (MemoryType) Type() protoreflect.EnumType {
	return &file_memory_memory_proto_enumTypes[0]
}

func (x MemoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryType.Descriptor instead.
func (MemoryType) EnumDescriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{0}
}

// 记忆条目
type MemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          MemoryType             `protobuf:"varint,4,opt,name=type,proto3,enum=memory.MemoryType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Importance    float64                `protobuf:"fixed64,6,opt,name=importance,proto3" json:"importance,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_memory_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MemoryEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryEntry) GetType() MemoryType {
	if x != nil {
		return x.Type
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (x *MemoryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryEntry) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MemoryEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 保存记忆请求
type SaveMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          MemoryType             `protobuf:"varint,3,opt,name=type,proto3,enum=memory.MemoryType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Importance    float64                `protobuf:"fixed64,5,opt,name=importance,proto3" json:"importance,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMemoryRequest) Reset() {
	*x = SaveMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemoryRequest) ProtoMessage() {}

func (x *SaveMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemoryRequest.ProtoReflect.Descriptor instead.
func (*SaveMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SaveMemoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SaveMemoryRequest) GetType() MemoryType {
	if x != nil {
		return x.Type
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (x *SaveMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveMemoryRequest) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SaveMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 保存记忆响应
type SaveMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMemoryResponse) Reset() {
	*x = SaveMemoryResponse{}
	mi := &file_memory_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemoryResponse) ProtoMessage() {}

func (x *SaveMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemoryResponse.ProtoReflect.Descriptor instead.
func (*SaveMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{2}
}

func (x *SaveMemoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveMemoryResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 召回记忆请求
type RecallMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMemoryRequest) Reset() {
	*x = RecallMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMemoryRequest) ProtoMessage() {}

func (x *RecallMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMemoryRequest.ProtoReflect.Descriptor instead.
func (*RecallMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RecallMemoryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecallMemoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RecallMemoryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RecallMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 召回记忆响应
type RecallMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*MemoryEntry         `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMemoryResponse) Reset() {
	*x = RecallMemoryResponse{}
	mi := &file_memory_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMemoryResponse) ProtoMessage() {}

func (x *RecallMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMemoryResponse.ProtoReflect.Descriptor instead.
func (*RecallMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RecallMemoryResponse) GetMemories() []*MemoryEntry {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *RecallMemoryResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// 获取会话记忆请求
type GetSessionMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionMemoryRequest) Reset() {
	*x = GetSessionMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionMemoryRequest) ProtoMessage() {}

func (x *GetSessionMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetSessionMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 删除会话记忆请求
type DeleteSessionMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionMemoryRequest) Reset() {
	*x = DeleteSessionMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionMemoryRequest) ProtoMessage() {}

func (x *DeleteSessionMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSessionMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 获取所有记忆请求（用户级别）
type GetAllMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMemoriesRequest) Reset() {
	*x = GetAllMemoriesRequest{}
	mi := &file_memory_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMemoriesRequest) ProtoMessage() {}

func (x *GetAllMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMemoriesRequest.ProtoReflect.Descriptor instead.
func (*GetAllMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllMemoriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 删除单条记忆请求
type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMemoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 批量保存记忆请求
type SaveMemoryBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*SaveMemoryRequest   `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMemoryBatchRequest) Reset() {
	*x = SaveMemoryBatchRequest{}
	mi := &file_memory_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMemoryBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemoryBatchRequest) ProtoMessage() {}

func (x *SaveMemoryBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemoryBatchRequest.ProtoReflect.Descriptor instead.
func (*SaveMemoryBatchRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{9}
}

func (x *SaveMemoryBatchRequest) GetMemories() []*SaveMemoryRequest {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *SaveMemoryBatchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 批量保存记忆响应
type SaveMemoryBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMemoryBatchResponse) Reset() {
	*x = SaveMemoryBatchResponse{}
	mi := &file_memory_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMemoryBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemoryBatchResponse) ProtoMessage() {}

func (x *SaveMemoryBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemoryBatchResponse.ProtoReflect.Descriptor instead.
func (*SaveMemoryBatchResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{10}
}

func (x *SaveMemoryBatchResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SaveMemoryBatchResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_memory_memory_proto protoreflect.FileDescriptor

const file_memory_memory_proto_rawDesc = "" +
	"\n" +
	"\x13memory/memory.proto\x12\x06memory\x1a\x13common/common.proto\"\xd8\x01\n" +
	"\vMemoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.memory.MemoryTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"importance\x18\x06 \x01(\x01R\n" +
	"importance\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xcc\x01\n" +
	"\x11SaveMemoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.memory.MemoryTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x01R\n" +
	"importance\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"C\n" +
	"\x12SaveMemoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"\x97\x01\n" +
	"\x13RecallMemoryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"f\n" +
	"\x14RecallMemoryResponse\x12/\n" +
	"\bmemories\x18\x01 \x03(\v2\x13.memory.MemoryEntryR\bmemories\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\"U\n" +
	"\x17GetSessionMemoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"X\n" +
	"\x1aDeleteSessionMemoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"4\n" +
	"\x15GetAllMemoriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"B\n" +
	"\x13DeleteMemoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"l\n" +
	"\x16SaveMemoryBatchRequest\x125\n" +
	"\bmemories\x18\x01 \x03(\v2\x19.memory.SaveMemoryRequestR\bmemories\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"J\n" +
	"\x17SaveMemoryBatchResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt*s\n" +
	"\n" +
	"MemoryType\x12\x1b\n" +
	"\x17MEMORY_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MEMORY_TYPE_IMPORTANT\x10\x01\x12\x17\n" +
	"\x13MEMORY_TYPE_SUMMARY\x10\x02\x12\x14\n" +
	"\x10MEMORY_TYPE_FACT\x10\x032\x89\x04\n" +
	"\rMemoryService\x12=\n" +
	"\x04Save\x12\x19.memory.SaveMemoryRequest\x1a\x1a.memory.SaveMemoryResponse\x12L\n" +
	"\tSaveBatch\x12\x1e.memory.SaveMemoryBatchRequest\x1a\x1f.memory.SaveMemoryBatchResponse\x12C\n" +
	"\x06Recall\x12\x1b.memory.RecallMemoryRequest\x1a\x1c.memory.RecallMemoryResponse\x12Q\n" +
	"\x10GetSessionMemory\x12\x1f.memory.GetSessionMemoryRequest\x1a\x1c.memory.RecallMemoryResponse\x12H\n" +
	"\x13DeleteSessionMemory\x12\".memory.DeleteSessionMemoryRequest\x1a\r.common.Empty\x12M\n" +
	"\x0eGetAllMemories\x12\x1d.memory.GetAllMemoriesRequest\x1a\x1c.memory.RecallMemoryResponse\x12:\n" +
	"\fDeleteMemory\x12\x1b.memory.DeleteMemoryRequest\x1a\r.common.EmptyB\x1eZ\x1cagent-platform/pkg/pb/memoryb\x06proto3"

var (
	file_memory_memory_proto_rawDescOnce sync.Once
	file_memory_memory_proto_rawDescData []byte
)

func file_memory_memory_proto_rawDescGZIP() []byte {
	file_memory_memory_proto_rawDescOnce.Do(func() {
		file_memory_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_memory_proto_rawDesc), len(file_memory_memory_proto_rawDesc)))
	})
	return file_memory_memory_proto_rawDescData
}

var file_memory_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_memory_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_memory_memory_proto_goTypes = []any{
	(MemoryType)(0),                    // 0: memory.MemoryType
	(*MemoryEntry)(nil),                // 1: memory.MemoryEntry
	(*SaveMemoryRequest)(nil),          // 2: memory.SaveMemoryRequest
	(*SaveMemoryResponse)(nil),         // 3: memory.SaveMemoryResponse
	(*RecallMemoryRequest)(nil),        // 4: memory.RecallMemoryRequest
	(*RecallMemoryResponse)(nil),       // 5: memory.RecallMemoryResponse
	(*GetSessionMemoryRequest)(nil),    // 6: memory.GetSessionMemoryRequest
	(*DeleteSessionMemoryRequest)(nil), // 7: memory.DeleteSessionMemoryRequest
	(*GetAllMemoriesRequest)(nil),      // 8: memory.GetAllMemoriesRequest
	(*DeleteMemoryRequest)(nil),        // 9: memory.DeleteMemoryRequest
	(*SaveMemoryBatchRequest)(nil),     // 10: memory.SaveMemoryBatchRequest
	(*SaveMemoryBatchResponse)(nil),    // 11: memory.SaveMemoryBatchResponse
	(*common.Empty)(nil),               // 12: common.Empty
}
var file_memory_memory_proto_depIdxs = []int32{
	0,  // 0: memory.MemoryEntry.type:type_name -> memory.MemoryType
	0,  // 1: memory.SaveMemoryRequest.type:type_name -> memory.MemoryType
	1,  // 2: memory.RecallMemoryResponse.memories:type_name -> memory.MemoryEntry
	2,  // 3: memory.SaveMemoryBatchRequest.memories:type_name -> memory.SaveMemoryRequest
	2,  // 4: memory.MemoryService.Save:input_type -> memory.SaveMemoryRequest
	10, // 5: memory.MemoryService.SaveBatch:input_type -> memory.SaveMemoryBatchRequest
	4,  // 6: memory.MemoryService.Recall:input_type -> memory.RecallMemoryRequest
	6,  // 7: memory.MemoryService.GetSessionMemory:input_type -> memory.GetSessionMemoryRequest
	7,  // 8: memory.MemoryService.DeleteSessionMemory:input_type -> memory.DeleteSessionMemoryRequest
	8,  // 9: memory.MemoryService.GetAllMemories:input_type -> memory.GetAllMemoriesRequest
	9,  // 10: memory.MemoryService.DeleteMemory:input_type -> memory.DeleteMemoryRequest
	3,  // 11: memory.MemoryService.Save:output_type -> memory.SaveMemoryResponse
	11, // 12: memory.MemoryService.SaveBatch:output_type -> memory.SaveMemoryBatchResponse
	5,  // 13: memory.MemoryService.Recall:output_type -> memory.RecallMemoryResponse
	5,  // 14: memory.MemoryService.GetSessionMemory:output_type -> memory.RecallMemoryResponse
	12, // 15: memory.MemoryService.DeleteSessionMemory:output_type -> common.Empty
	5,  // 16: memory.MemoryService.GetAllMemories:output_type -> memory.RecallMemoryResponse
	12, // 17: memory.MemoryService.DeleteMemory:output_type -> common.Empty
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_memory_memory_proto_init() }
func file_memory_memory_proto_init() {
	if File_memory_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_memory_proto_rawDesc), len(file_memory_memory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_memory_proto_goTypes,
		DependencyIndexes: file_memory_memory_proto_depIdxs,
		EnumInfos:         file_memory_memory_proto_enumTypes,
		MessageInfos:      file_memory_memory_proto_msgTypes,
	}.Build()
	File_memory_memory_proto = out.File
	file_memory_memory_proto_goTypes = nil
	file_memory_memory_proto_depIdxs = nil
}
