// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: memory/memory.proto

package memory

import (
	common "agent-platform/pkg/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_Save_FullMethodName                = "/memory.MemoryService/Save"
	MemoryService_SaveBatch_FullMethodName           = "/memory.MemoryService/SaveBatch"
	MemoryService_Recall_FullMethodName              = "/memory.MemoryService/Recall"
	MemoryService_GetSessionMemory_FullMethodName    = "/memory.MemoryService/GetSessionMemory"
	MemoryService_DeleteSessionMemory_FullMethodName = "/memory.MemoryService/DeleteSessionMemory"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Memory 服务定义
type MemoryServiceClient interface {
	// 保存记忆
	Save(ctx context.Context, in *SaveMemoryRequest, opts ...grpc.CallOption) (*SaveMemoryResponse, error)
	SaveBatch(ctx context.Context, in *SaveMemoryBatchRequest, opts ...grpc.CallOption) (*SaveMemoryBatchResponse, error)
	// 召回记忆
	Recall(ctx context.Context, in *RecallMemoryRequest, opts ...grpc.CallOption) (*RecallMemoryResponse, error)
	// 会话记忆管理
	GetSessionMemory(ctx context.Context, in *GetSessionMemoryRequest, opts ...grpc.CallOption) (*RecallMemoryResponse, error)
	DeleteSessionMemory(ctx context.Context, in *DeleteSessionMemoryRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) Save(ctx context.Context, in *SaveMemoryRequest, opts ...grpc.CallOption) (*SaveMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SaveBatch(ctx context.Context, in *SaveMemoryBatchRequest, opts ...grpc.CallOption) (*SaveMemoryBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMemoryBatchResponse)
	err := c.cc.Invoke(ctx, MemoryService_SaveBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Recall(ctx context.Context, in *RecallMemoryRequest, opts ...grpc.CallOption) (*RecallMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetSessionMemory(ctx context.Context, in *GetSessionMemoryRequest, opts ...grpc.CallOption) (*RecallMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetSessionMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteSessionMemory(ctx context.Context, in *DeleteSessionMemoryRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, MemoryService_DeleteSessionMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
//
// Memory 服务定义
type MemoryServiceServer interface {
	// 保存记忆
	Save(context.Context, *SaveMemoryRequest) (*SaveMemoryResponse, error)
	SaveBatch(context.Context, *SaveMemoryBatchRequest) (*SaveMemoryBatchResponse, error)
	// 召回记忆
	Recall(context.Context, *RecallMemoryRequest) (*RecallMemoryResponse, error)
	// 会话记忆管理
	GetSessionMemory(context.Context, *GetSessionMemoryRequest) (*RecallMemoryResponse, error)
	DeleteSessionMemory(context.Context, *DeleteSessionMemoryRequest) (*common.Empty, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) Save(context.Context, *SaveMemoryRequest) (*SaveMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedMemoryServiceServer) SaveBatch(context.Context, *SaveMemoryBatchRequest) (*SaveMemoryBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBatch not implemented")
}
func (UnimplementedMemoryServiceServer) Recall(context.Context, *RecallMemoryRequest) (*RecallMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedMemoryServiceServer) GetSessionMemory(context.Context, *GetSessionMemoryRequest) (*RecallMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionMemory not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteSessionMemory(context.Context, *DeleteSessionMemoryRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSessionMemory not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Save(ctx, req.(*SaveMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SaveBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMemoryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SaveBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SaveBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SaveBatch(ctx, req.(*SaveMemoryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Recall(ctx, req.(*RecallMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetSessionMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetSessionMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetSessionMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetSessionMemory(ctx, req.(*GetSessionMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteSessionMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteSessionMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteSessionMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteSessionMemory(ctx, req.(*DeleteSessionMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memory.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _MemoryService_Save_Handler,
		},
		{
			MethodName: "SaveBatch",
			Handler:    _MemoryService_SaveBatch_Handler,
		},
		{
			MethodName: "Recall",
			Handler:    _MemoryService_Recall_Handler,
		},
		{
			MethodName: "GetSessionMemory",
			Handler:    _MemoryService_GetSessionMemory_Handler,
		},
		{
			MethodName: "DeleteSessionMemory",
			Handler:    _MemoryService_DeleteSessionMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory/memory.proto",
}
