// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/agent/agent.proto

package agent

import (
	common "agent-platform/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent definition
type Agent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Instructions      string                 `protobuf:"bytes,4,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Tools             []string               `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	Handoffs          []string               `protobuf:"bytes,6,rep,name=handoffs,proto3" json:"handoffs,omitempty"`
	Model             string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	MaxTokens         int32                  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature       float64                `protobuf:"fixed64,9,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt         int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PromptTemplateKey string                 `protobuf:"bytes,13,opt,name=prompt_template_key,json=promptTemplateKey,proto3" json:"prompt_template_key,omitempty"` // References a template in Prompt Management
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Agent) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *Agent) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Agent) GetHandoffs() []string {
	if x != nil {
		return x.Handoffs
	}
	return nil
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *Agent) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Agent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Agent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Agent) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Agent) GetPromptTemplateKey() string {
	if x != nil {
		return x.PromptTemplateKey
	}
	return ""
}

// Agent execution record
type AgentExecutionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Thought       string                 `protobuf:"bytes,3,opt,name=thought,proto3" json:"thought,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Arguments     string                 `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	HandoffTo     string                 `protobuf:"bytes,7,opt,name=handoff_to,json=handoffTo,proto3" json:"handoff_to,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,8,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	StartedAt     int64                  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs    int64                  `protobuf:"varint,11,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecutionRecord) Reset() {
	*x = AgentExecutionRecord{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecutionRecord) ProtoMessage() {}

func (x *AgentExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecutionRecord.ProtoReflect.Descriptor instead.
func (*AgentExecutionRecord) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentExecutionRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentExecutionRecord) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentExecutionRecord) GetThought() string {
	if x != nil {
		return x.Thought
	}
	return ""
}

func (x *AgentExecutionRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentExecutionRecord) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *AgentExecutionRecord) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentExecutionRecord) GetHandoffTo() string {
	if x != nil {
		return x.HandoffTo
	}
	return ""
}

func (x *AgentExecutionRecord) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *AgentExecutionRecord) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *AgentExecutionRecord) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *AgentExecutionRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Execution context
type ExecutionContext struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                  `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                  `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                  `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Variables     map[string]string       `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages      []*Message              `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`
	AgentHistory  []*AgentExecutionRecord `protobuf:"bytes,7,rep,name=agent_history,json=agentHistory,proto3" json:"agent_history,omitempty"`
	CurrentAgent  string                  `protobuf:"bytes,8,opt,name=current_agent,json=currentAgent,proto3" json:"current_agent,omitempty"`
	EntryAgent    string                  `protobuf:"bytes,9,opt,name=entry_agent,json=entryAgent,proto3" json:"entry_agent,omitempty"`
	Status        string                  `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	TotalTokens   int32                   `protobuf:"varint,11,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCost     float64                 `protobuf:"fixed64,12,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Error         string                  `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     int64                   `protobuf:"varint,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                   `protobuf:"varint,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	StepCount     int32                   `protobuf:"varint,16,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecutionContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExecutionContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecutionContext) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ExecutionContext) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ExecutionContext) GetAgentHistory() []*AgentExecutionRecord {
	if x != nil {
		return x.AgentHistory
	}
	return nil
}

func (x *ExecutionContext) GetCurrentAgent() string {
	if x != nil {
		return x.CurrentAgent
	}
	return ""
}

func (x *ExecutionContext) GetEntryAgent() string {
	if x != nil {
		return x.EntryAgent
	}
	return ""
}

func (x *ExecutionContext) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionContext) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ExecutionContext) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ExecutionContext) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutionContext) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ExecutionContext) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *ExecutionContext) GetStepCount() int32 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

// Message
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ToolId        string                 `protobuf:"bytes,4,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

// Tool call
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Register Agent Request
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// Register Agent Response
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// Unregister Agent Request
type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Unregister Agent Response
type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get Agent Request
type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Get Agent Response
type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// List Agents Request
type ListAgentsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListAgentsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// List Agents Response
type ListAgentsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Agents        []*Agent                   `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Execute Request
type ExecuteRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SessionId   string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId    string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId      string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message     string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	EntryAgent  string                 `protobuf:"bytes,5,opt,name=entry_agent,json=entryAgent,proto3" json:"entry_agent,omitempty"`
	ContextVars map[string]string      `protobuf:"bytes,6,rep,name=context_vars,json=contextVars,proto3" json:"context_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Explicit task goal. The planner decomposes it and the system prompt
	// surfaces it each step so the agent knows what it is working toward.
	Goal string `protobuf:"bytes,7,opt,name=goal,proto3" json:"goal,omitempty"`
	// Checkable completion condition. The verifier gates "done" on this: the
	// agent is not allowed to stop until the criteria are met.
	SuccessCriteria string `protobuf:"bytes,8,opt,name=success_criteria,json=successCriteria,proto3" json:"success_criteria,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExecuteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteRequest) GetEntryAgent() string {
	if x != nil {
		return x.EntryAgent
	}
	return ""
}

func (x *ExecuteRequest) GetContextVars() map[string]string {
	if x != nil {
		return x.ContextVars
	}
	return nil
}

func (x *ExecuteRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *ExecuteRequest) GetSuccessCriteria() string {
	if x != nil {
		return x.SuccessCriteria
	}
	return ""
}

// Execute Response
type ExecuteResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ContextId     string                  `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	SessionId     string                  `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Response      string                  `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	AgentHistory  []*AgentExecutionRecord `protobuf:"bytes,4,rep,name=agent_history,json=agentHistory,proto3" json:"agent_history,omitempty"`
	TotalTokens   int32                   `protobuf:"varint,5,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCost     float64                 `protobuf:"fixed64,6,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Status        string                  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                  `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteResponse) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ExecuteResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ExecuteResponse) GetAgentHistory() []*AgentExecutionRecord {
	if x != nil {
		return x.AgentHistory
	}
	return nil
}

func (x *ExecuteResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ExecuteResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get Context Request
type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetContextRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

// Get Context Response
type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ExecutionContext      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *GetContextResponse) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// Execute Stream Request
type ExecuteStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	EntryAgent      string                 `protobuf:"bytes,5,opt,name=entry_agent,json=entryAgent,proto3" json:"entry_agent,omitempty"`
	ContextVars     map[string]string      `protobuf:"bytes,6,rep,name=context_vars,json=contextVars,proto3" json:"context_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Goal            string                 `protobuf:"bytes,7,opt,name=goal,proto3" json:"goal,omitempty"`
	SuccessCriteria string                 `protobuf:"bytes,8,opt,name=success_criteria,json=successCriteria,proto3" json:"success_criteria,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteStreamRequest) Reset() {
	*x = ExecuteStreamRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamRequest) ProtoMessage() {}

func (x *ExecuteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteStreamRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExecuteStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteStreamRequest) GetEntryAgent() string {
	if x != nil {
		return x.EntryAgent
	}
	return ""
}

func (x *ExecuteStreamRequest) GetContextVars() map[string]string {
	if x != nil {
		return x.ContextVars
	}
	return nil
}

func (x *ExecuteStreamRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *ExecuteStreamRequest) GetSuccessCriteria() string {
	if x != nil {
		return x.SuccessCriteria
	}
	return ""
}

// Execute Stream Chunk
type ExecuteStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "agent_step", "tool_call", "handoff", "response"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Step          *AgentExecutionRecord  `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	ToolCall      *ToolCall              `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	CurrentAgent  string                 `protobuf:"bytes,5,opt,name=current_agent,json=currentAgent,proto3" json:"current_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStreamChunk) Reset() {
	*x = ExecuteStreamChunk{}
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamChunk) ProtoMessage() {}

func (x *ExecuteStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamChunk.ProtoReflect.Descriptor instead.
func (*ExecuteStreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteStreamChunk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecuteStreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteStreamChunk) GetStep() *AgentExecutionRecord {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *ExecuteStreamChunk) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *ExecuteStreamChunk) GetCurrentAgent() string {
	if x != nil {
		return x.CurrentAgent
	}
	return ""
}

// Resume Request - resume an execution from a saved checkpoint
type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ResumeRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

// Resume Response - mirrors ExecuteResponse
type ResumeResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ContextId     string                  `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	SessionId     string                  `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Response      string                  `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	AgentHistory  []*AgentExecutionRecord `protobuf:"bytes,4,rep,name=agent_history,json=agentHistory,proto3" json:"agent_history,omitempty"`
	TotalTokens   int32                   `protobuf:"varint,5,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCost     float64                 `protobuf:"fixed64,6,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Status        string                  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                  `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ResumeResponse) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ResumeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ResumeResponse) GetAgentHistory() []*AgentExecutionRecord {
	if x != nil {
		return x.AgentHistory
	}
	return nil
}

func (x *ResumeResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ResumeResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ResumeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\x1a\x19proto/common/common.proto\"\xdd\x03\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\finstructions\x18\x04 \x01(\tR\finstructions\x12\x14\n" +
	"\x05tools\x18\x05 \x03(\tR\x05tools\x12\x1a\n" +
	"\bhandoffs\x18\x06 \x03(\tR\bhandoffs\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\t \x01(\x01R\vtemperature\x126\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1a.agent.Agent.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12.\n" +
	"\x13prompt_template_key\x18\r \x01(\tR\x11promptTemplateKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x02\n" +
	"\x14AgentExecutionRecord\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x18\n" +
	"\athought\x18\x03 \x01(\tR\athought\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1c\n" +
	"\targuments\x18\x05 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"handoff_to\x18\a \x01(\tR\thandoffTo\x12\x1f\n" +
	"\vtokens_used\x18\b \x01(\x05R\n" +
	"tokensUsed\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\x03R\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\v \x01(\x03R\n" +
	"durationMs\"\x80\x05\n" +
	"\x10ExecutionContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12D\n" +
	"\tvariables\x18\x05 \x03(\v2&.agent.ExecutionContext.VariablesEntryR\tvariables\x12*\n" +
	"\bmessages\x18\x06 \x03(\v2\x0e.agent.MessageR\bmessages\x12@\n" +
	"\ragent_history\x18\a \x03(\v2\x1b.agent.AgentExecutionRecordR\fagentHistory\x12#\n" +
	"\rcurrent_agent\x18\b \x01(\tR\fcurrentAgent\x12\x1f\n" +
	"\ventry_agent\x18\t \x01(\tR\n" +
	"entryAgent\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\ftotal_tokens\x18\v \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\f \x01(\x01R\ttotalCost\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\x0e \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x0f \x01(\x03R\vcompletedAt\x12\x1d\n" +
	"\n" +
	"step_count\x18\x10 \x01(\x05R\tstepCount\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\atool_id\x18\x04 \x01(\tR\x06toolId\"|\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\":\n" +
	"\x14RegisterAgentRequest\x12\"\n" +
	"\x05agent\x18\x01 \x01(\v2\f.agent.AgentR\x05agent\";\n" +
	"\x15RegisterAgentResponse\x12\"\n" +
	"\x05agent\x18\x01 \x01(\v2\f.agent.AgentR\x05agent\"3\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"3\n" +
	"\x17UnregisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"6\n" +
	"\x10GetAgentResponse\x12\"\n" +
	"\x05agent\x18\x01 \x01(\v2\f.agent.AgentR\x05agent\"N\n" +
	"\x11ListAgentsRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"v\n" +
	"\x12ListAgentsResponse\x12$\n" +
	"\x06agents\x18\x01 \x03(\v2\f.agent.AgentR\x06agents\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"\xea\x02\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\ventry_agent\x18\x05 \x01(\tR\n" +
	"entryAgent\x12I\n" +
	"\fcontext_vars\x18\x06 \x03(\v2&.agent.ExecuteRequest.ContextVarsEntryR\vcontextVars\x12\x12\n" +
	"\x04goal\x18\a \x01(\tR\x04goal\x12)\n" +
	"\x10success_criteria\x18\b \x01(\tR\x0fsuccessCriteria\x1a>\n" +
	"\x10ContextVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x02\n" +
	"\x0fExecuteResponse\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12@\n" +
	"\ragent_history\x18\x04 \x03(\v2\x1b.agent.AgentExecutionRecordR\fagentHistory\x12!\n" +
	"\ftotal_tokens\x18\x05 \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x06 \x01(\x01R\ttotalCost\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"2\n" +
	"\x11GetContextRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\"G\n" +
	"\x12GetContextResponse\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.agent.ExecutionContextR\acontext\"\xf6\x02\n" +
	"\x14ExecuteStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\ventry_agent\x18\x05 \x01(\tR\n" +
	"entryAgent\x12O\n" +
	"\fcontext_vars\x18\x06 \x03(\v2,.agent.ExecuteStreamRequest.ContextVarsEntryR\vcontextVars\x12\x12\n" +
	"\x04goal\x18\a \x01(\tR\x04goal\x12)\n" +
	"\x10success_criteria\x18\b \x01(\tR\x0fsuccessCriteria\x1a>\n" +
	"\x10ContextVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x12ExecuteStreamChunk\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12/\n" +
	"\x04step\x18\x03 \x01(\v2\x1b.agent.AgentExecutionRecordR\x04step\x12,\n" +
	"\ttool_call\x18\x04 \x01(\v2\x0f.agent.ToolCallR\btoolCall\x12#\n" +
	"\rcurrent_agent\x18\x05 \x01(\tR\fcurrentAgent\"4\n" +
	"\rResumeRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\"\x9c\x02\n" +
	"\x0eResumeResponse\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12@\n" +
	"\ragent_history\x18\x04 \x03(\v2\x1b.agent.AgentExecutionRecordR\fagentHistory\x12!\n" +
	"\ftotal_tokens\x18\x05 \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x06 \x01(\x01R\ttotalCost\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error2\xab\x04\n" +
	"\fAgentService\x12J\n" +
	"\rRegisterAgent\x12\x1b.agent.RegisterAgentRequest\x1a\x1c.agent.RegisterAgentResponse\x12P\n" +
	"\x0fUnregisterAgent\x12\x1d.agent.UnregisterAgentRequest\x1a\x1e.agent.UnregisterAgentResponse\x12;\n" +
	"\bGetAgent\x12\x16.agent.GetAgentRequest\x1a\x17.agent.GetAgentResponse\x12A\n" +
	"\n" +
	"ListAgents\x12\x18.agent.ListAgentsRequest\x1a\x19.agent.ListAgentsResponse\x128\n" +
	"\aExecute\x12\x15.agent.ExecuteRequest\x1a\x16.agent.ExecuteResponse\x12I\n" +
	"\rExecuteStream\x12\x1b.agent.ExecuteStreamRequest\x1a\x19.agent.ExecuteStreamChunk0\x01\x12A\n" +
	"\n" +
	"GetContext\x12\x18.agent.GetContextRequest\x1a\x19.agent.GetContextResponse\x125\n" +
	"\x06Resume\x12\x14.agent.ResumeRequest\x1a\x15.agent.ResumeResponseB\x1dZ\x1bagent-platform/pkg/pb/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_agent_agent_proto_goTypes = []any{
	(*Agent)(nil),                     // 0: agent.Agent
	(*AgentExecutionRecord)(nil),      // 1: agent.AgentExecutionRecord
	(*ExecutionContext)(nil),          // 2: agent.ExecutionContext
	(*Message)(nil),                   // 3: agent.Message
	(*ToolCall)(nil),                  // 4: agent.ToolCall
	(*RegisterAgentRequest)(nil),      // 5: agent.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),     // 6: agent.RegisterAgentResponse
	(*UnregisterAgentRequest)(nil),    // 7: agent.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil),   // 8: agent.UnregisterAgentResponse
	(*GetAgentRequest)(nil),           // 9: agent.GetAgentRequest
	(*GetAgentResponse)(nil),          // 10: agent.GetAgentResponse
	(*ListAgentsRequest)(nil),         // 11: agent.ListAgentsRequest
	(*ListAgentsResponse)(nil),        // 12: agent.ListAgentsResponse
	(*ExecuteRequest)(nil),            // 13: agent.ExecuteRequest
	(*ExecuteResponse)(nil),           // 14: agent.ExecuteResponse
	(*GetContextRequest)(nil),         // 15: agent.GetContextRequest
	(*GetContextResponse)(nil),        // 16: agent.GetContextResponse
	(*ExecuteStreamRequest)(nil),      // 17: agent.ExecuteStreamRequest
	(*ExecuteStreamChunk)(nil),        // 18: agent.ExecuteStreamChunk
	(*ResumeRequest)(nil),             // 19: agent.ResumeRequest
	(*ResumeResponse)(nil),            // 20: agent.ResumeResponse
	nil,                               // 21: agent.Agent.MetadataEntry
	nil,                               // 22: agent.ExecutionContext.VariablesEntry
	nil,                               // 23: agent.ExecuteRequest.ContextVarsEntry
	nil,                               // 24: agent.ExecuteStreamRequest.ContextVarsEntry
	(*common.PaginationRequest)(nil),  // 25: common.PaginationRequest
	(*common.PaginationResponse)(nil), // 26: common.PaginationResponse
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	21, // 0: agent.Agent.metadata:type_name -> agent.Agent.MetadataEntry
	22, // 1: agent.ExecutionContext.variables:type_name -> agent.ExecutionContext.VariablesEntry
	3,  // 2: agent.ExecutionContext.messages:type_name -> agent.Message
	1,  // 3: agent.ExecutionContext.agent_history:type_name -> agent.AgentExecutionRecord
	0,  // 4: agent.RegisterAgentRequest.agent:type_name -> agent.Agent
	0,  // 5: agent.RegisterAgentResponse.agent:type_name -> agent.Agent
	0,  // 6: agent.GetAgentResponse.agent:type_name -> agent.Agent
	25, // 7: agent.ListAgentsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 8: agent.ListAgentsResponse.agents:type_name -> agent.Agent
	26, // 9: agent.ListAgentsResponse.pagination:type_name -> common.PaginationResponse
	23, // 10: agent.ExecuteRequest.context_vars:type_name -> agent.ExecuteRequest.ContextVarsEntry
	1,  // 11: agent.ExecuteResponse.agent_history:type_name -> agent.AgentExecutionRecord
	2,  // 12: agent.GetContextResponse.context:type_name -> agent.ExecutionContext
	24, // 13: agent.ExecuteStreamRequest.context_vars:type_name -> agent.ExecuteStreamRequest.ContextVarsEntry
	1,  // 14: agent.ExecuteStreamChunk.step:type_name -> agent.AgentExecutionRecord
	4,  // 15: agent.ExecuteStreamChunk.tool_call:type_name -> agent.ToolCall
	1,  // 16: agent.ResumeResponse.agent_history:type_name -> agent.AgentExecutionRecord
	5,  // 17: agent.AgentService.RegisterAgent:input_type -> agent.RegisterAgentRequest
	7,  // 18: agent.AgentService.UnregisterAgent:input_type -> agent.UnregisterAgentRequest
	9,  // 19: agent.AgentService.GetAgent:input_type -> agent.GetAgentRequest
	11, // 20: agent.AgentService.ListAgents:input_type -> agent.ListAgentsRequest
	13, // 21: agent.AgentService.Execute:input_type -> agent.ExecuteRequest
	17, // 22: agent.AgentService.ExecuteStream:input_type -> agent.ExecuteStreamRequest
	15, // 23: agent.AgentService.GetContext:input_type -> agent.GetContextRequest
	19, // 24: agent.AgentService.Resume:input_type -> agent.ResumeRequest
	6,  // 25: agent.AgentService.RegisterAgent:output_type -> agent.RegisterAgentResponse
	8,  // 26: agent.AgentService.UnregisterAgent:output_type -> agent.UnregisterAgentResponse
	10, // 27: agent.AgentService.GetAgent:output_type -> agent.GetAgentResponse
	12, // 28: agent.AgentService.ListAgents:output_type -> agent.ListAgentsResponse
	14, // 29: agent.AgentService.Execute:output_type -> agent.ExecuteResponse
	18, // 30: agent.AgentService.ExecuteStream:output_type -> agent.ExecuteStreamChunk
	16, // 31: agent.AgentService.GetContext:output_type -> agent.GetContextResponse
	20, // 32: agent.AgentService.Resume:output_type -> agent.ResumeResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
