// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/chat/chat.proto

package chat

import (
	common "agent-platform/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent 执行状态
type AgentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thought       string                 `protobuf:"bytes,1,opt,name=thought,proto3" json:"thought,omitempty"`     // 思考过程
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`       // 选择的工具/动作
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // 参数 (JSON)
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`       // 执行结果
	Step          int32                  `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`          // 步骤编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *AgentState) GetThought() string {
	if x != nil {
		return x.Thought
	}
	return ""
}

func (x *AgentState) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentState) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *AgentState) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentState) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

// 工具调用
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // pending, running, completed, error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentTrace    []*AgentState          `protobuf:"bytes,6,rep,name=agent_trace,json=agentTrace,proto3" json:"agent_trace,omitempty"` // Agent 执行轨迹
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetAgentTrace() []*AgentState {
	if x != nil {
		return x.AgentTrace
	}
	return nil
}

// 会话
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 对话请求
type ChatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt      string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ToolIds           []string               `protobuf:"bytes,5,rep,name=tool_ids,json=toolIds,proto3" json:"tool_ids,omitempty"`
	Stream            bool                   `protobuf:"varint,6,opt,name=stream,proto3" json:"stream,omitempty"`
	TenantId          string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId            string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EnableAgent       bool                   `protobuf:"varint,9,opt,name=enable_agent,json=enableAgent,proto3" json:"enable_agent,omitempty"`                     // 是否启用 Agent 模式
	MaxSteps          int32                  `protobuf:"varint,10,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`                             // Agent 最大步骤数
	PromptTemplateKey string                 `protobuf:"bytes,11,opt,name=prompt_template_key,json=promptTemplateKey,proto3" json:"prompt_template_key,omitempty"` // Prompt管理的模板key
	PromptVariables   string                 `protobuf:"bytes,12,opt,name=prompt_variables,json=promptVariables,proto3" json:"prompt_variables,omitempty"`         // JSON格式的模板变量
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetToolIds() []string {
	if x != nil {
		return x.ToolIds
	}
	return nil
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetEnableAgent() bool {
	if x != nil {
		return x.EnableAgent
	}
	return false
}

func (x *ChatRequest) GetMaxSteps() int32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *ChatRequest) GetPromptTemplateKey() string {
	if x != nil {
		return x.PromptTemplateKey
	}
	return ""
}

func (x *ChatRequest) GetPromptVariables() string {
	if x != nil {
		return x.PromptVariables
	}
	return ""
}

// 对话响应
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	AgentStates   []*AgentState          `protobuf:"bytes,7,rep,name=agent_states,json=agentStates,proto3" json:"agent_states,omitempty"` // Agent 执行状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ChatResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ChatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatResponse) GetAgentStates() []*AgentState {
	if x != nil {
		return x.AgentStates
	}
	return nil
}

// 流式响应块
type ChatStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "thought", "action", "result", "final"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	State         *AgentState            `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamChunk) Reset() {
	*x = ChatStreamChunk{}
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamChunk) ProtoMessage() {}

func (x *ChatStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamChunk.ProtoReflect.Descriptor instead.
func (*ChatStreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatStreamChunk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamChunk) GetState() *AgentState {
	if x != nil {
		return x.State
	}
	return nil
}

// 创建会话请求
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取会话请求
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 列出会话请求
type ListSessionsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TenantId      string                    `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                    `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSessionsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 列出会话响应
type ListSessionsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sessions      []*Session                 `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 删除会话请求
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 多 Agent 对话请求
type MultiAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MasterAgent   string                 `protobuf:"bytes,3,opt,name=master_agent,json=masterAgent,proto3" json:"master_agent,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentIds      []string               `protobuf:"bytes,6,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"` // 参与的 Agent ID 列表
	Strategy      string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`                 // 协作策略: sequential, parallel, debate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiAgentRequest) Reset() {
	*x = MultiAgentRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiAgentRequest) ProtoMessage() {}

func (x *MultiAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiAgentRequest.ProtoReflect.Descriptor instead.
func (*MultiAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{12}
}

func (x *MultiAgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MultiAgentRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MultiAgentRequest) GetMasterAgent() string {
	if x != nil {
		return x.MasterAgent
	}
	return ""
}

func (x *MultiAgentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MultiAgentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MultiAgentRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *MultiAgentRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// Agent 执行步骤
type AgentStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Step          int32                  `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	Thought       string                 `protobuf:"bytes,5,opt,name=thought,proto3" json:"thought,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStep) Reset() {
	*x = AgentStep{}
	mi := &file_proto_chat_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStep) ProtoMessage() {}

func (x *AgentStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStep.ProtoReflect.Descriptor instead.
func (*AgentStep) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{13}
}

func (x *AgentStep) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentStep) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentStep) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *AgentStep) GetThought() string {
	if x != nil {
		return x.Thought
	}
	return ""
}

// 多 Agent 对话响应
type MultiAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FinalAnswer   string                 `protobuf:"bytes,2,opt,name=final_answer,json=finalAnswer,proto3" json:"final_answer,omitempty"`
	Steps         []*AgentStep           `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiAgentResponse) Reset() {
	*x = MultiAgentResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiAgentResponse) ProtoMessage() {}

func (x *MultiAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiAgentResponse.ProtoReflect.Descriptor instead.
func (*MultiAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{14}
}

func (x *MultiAgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MultiAgentResponse) GetFinalAnswer() string {
	if x != nil {
		return x.FinalAnswer
	}
	return ""
}

func (x *MultiAgentResponse) GetSteps() []*AgentStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *MultiAgentResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *MultiAgentResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\x1a\x19proto/common/common.proto\"\x88\x01\n" +
	"\n" +
	"AgentState\x12\x18\n" +
	"\athought\x18\x01 \x01(\tR\athought\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x12\n" +
	"\x04step\x18\x05 \x01(\x05R\x04step\"|\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xc7\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12-\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x0e.chat.ToolCallR\ttoolCalls\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x121\n" +
	"\vagent_trace\x18\x06 \x03(\v2\x10.chat.AgentStateR\n" +
	"agentTrace\"\x98\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12)\n" +
	"\bmessages\x18\x03 \x03(\v2\r.chat.MessageR\bmessages\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\x85\x03\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x19\n" +
	"\btool_ids\x18\x05 \x03(\tR\atoolIds\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\bR\x06stream\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12!\n" +
	"\fenable_agent\x18\t \x01(\bR\venableAgent\x12\x1b\n" +
	"\tmax_steps\x18\n" +
	" \x01(\x05R\bmaxSteps\x12.\n" +
	"\x13prompt_template_key\x18\v \x01(\tR\x11promptTemplateKey\x12)\n" +
	"\x10prompt_variables\x18\f \x01(\tR\x0fpromptVariables\"\xfd\x01\n" +
	"\fChatResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12-\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x0e.chat.ToolCallR\ttoolCalls\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x123\n" +
	"\fagent_states\x18\a \x03(\v2\x10.chat.AgentStateR\vagentStates\"g\n" +
	"\x0fChatStreamChunk\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12&\n" +
	"\x05state\x18\x03 \x01(\v2\x10.chat.AgentStateR\x05state\"b\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"@\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x86\x01\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"}\n" +
	"\x14ListSessionsResponse\x12)\n" +
	"\bsessions\x18\x01 \x03(\v2\r.chat.SessionR\bsessions\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"C\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xde\x01\n" +
	"\x11MultiAgentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fmaster_agent\x18\x03 \x01(\tR\vmasterAgent\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1b\n" +
	"\tagent_ids\x18\x06 \x03(\tR\bagentIds\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\"\x84\x01\n" +
	"\tAgentStep\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x05R\x04step\x12\x18\n" +
	"\athought\x18\x05 \x01(\tR\athought\"\xb4\x01\n" +
	"\x12MultiAgentResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ffinal_answer\x18\x02 \x01(\tR\vfinalAnswer\x12%\n" +
	"\x05steps\x18\x03 \x03(\v2\x0f.chat.AgentStepR\x05steps\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost2\xb0\x03\n" +
	"\vChatService\x12-\n" +
	"\x04Chat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse\x128\n" +
	"\n" +
	"ChatStream\x12\x11.chat.ChatRequest\x1a\x15.chat.ChatStreamChunk0\x01\x12C\n" +
	"\x0eMultiAgentChat\x12\x17.chat.MultiAgentRequest\x1a\x18.chat.MultiAgentResponse\x12:\n" +
	"\rCreateSession\x12\x1a.chat.CreateSessionRequest\x1a\r.chat.Session\x124\n" +
	"\n" +
	"GetSession\x12\x17.chat.GetSessionRequest\x1a\r.chat.Session\x12E\n" +
	"\fListSessions\x12\x19.chat.ListSessionsRequest\x1a\x1a.chat.ListSessionsResponse\x12:\n" +
	"\rDeleteSession\x12\x1a.chat.DeleteSessionRequest\x1a\r.common.EmptyB\x1cZ\x1aagent-platform/pkg/pb/chatb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_chat_chat_proto_goTypes = []any{
	(*AgentState)(nil),                // 0: chat.AgentState
	(*ToolCall)(nil),                  // 1: chat.ToolCall
	(*Message)(nil),                   // 2: chat.Message
	(*Session)(nil),                   // 3: chat.Session
	(*ChatRequest)(nil),               // 4: chat.ChatRequest
	(*ChatResponse)(nil),              // 5: chat.ChatResponse
	(*ChatStreamChunk)(nil),           // 6: chat.ChatStreamChunk
	(*CreateSessionRequest)(nil),      // 7: chat.CreateSessionRequest
	(*GetSessionRequest)(nil),         // 8: chat.GetSessionRequest
	(*ListSessionsRequest)(nil),       // 9: chat.ListSessionsRequest
	(*ListSessionsResponse)(nil),      // 10: chat.ListSessionsResponse
	(*DeleteSessionRequest)(nil),      // 11: chat.DeleteSessionRequest
	(*MultiAgentRequest)(nil),         // 12: chat.MultiAgentRequest
	(*AgentStep)(nil),                 // 13: chat.AgentStep
	(*MultiAgentResponse)(nil),        // 14: chat.MultiAgentResponse
	(*common.PaginationRequest)(nil),  // 15: common.PaginationRequest
	(*common.PaginationResponse)(nil), // 16: common.PaginationResponse
	(*common.Empty)(nil),              // 17: common.Empty
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	1,  // 0: chat.Message.tool_calls:type_name -> chat.ToolCall
	0,  // 1: chat.Message.agent_trace:type_name -> chat.AgentState
	2,  // 2: chat.Session.messages:type_name -> chat.Message
	1,  // 3: chat.ChatResponse.tool_calls:type_name -> chat.ToolCall
	0,  // 4: chat.ChatResponse.agent_states:type_name -> chat.AgentState
	0,  // 5: chat.ChatStreamChunk.state:type_name -> chat.AgentState
	15, // 6: chat.ListSessionsRequest.pagination:type_name -> common.PaginationRequest
	3,  // 7: chat.ListSessionsResponse.sessions:type_name -> chat.Session
	16, // 8: chat.ListSessionsResponse.pagination:type_name -> common.PaginationResponse
	13, // 9: chat.MultiAgentResponse.steps:type_name -> chat.AgentStep
	4,  // 10: chat.ChatService.Chat:input_type -> chat.ChatRequest
	4,  // 11: chat.ChatService.ChatStream:input_type -> chat.ChatRequest
	12, // 12: chat.ChatService.MultiAgentChat:input_type -> chat.MultiAgentRequest
	7,  // 13: chat.ChatService.CreateSession:input_type -> chat.CreateSessionRequest
	8,  // 14: chat.ChatService.GetSession:input_type -> chat.GetSessionRequest
	9,  // 15: chat.ChatService.ListSessions:input_type -> chat.ListSessionsRequest
	11, // 16: chat.ChatService.DeleteSession:input_type -> chat.DeleteSessionRequest
	5,  // 17: chat.ChatService.Chat:output_type -> chat.ChatResponse
	6,  // 18: chat.ChatService.ChatStream:output_type -> chat.ChatStreamChunk
	14, // 19: chat.ChatService.MultiAgentChat:output_type -> chat.MultiAgentResponse
	3,  // 20: chat.ChatService.CreateSession:output_type -> chat.Session
	3,  // 21: chat.ChatService.GetSession:output_type -> chat.Session
	10, // 22: chat.ChatService.ListSessions:output_type -> chat.ListSessionsResponse
	17, // 23: chat.ChatService.DeleteSession:output_type -> common.Empty
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
