// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: harness/harness.proto

package harness

import (
	common "agent-platform/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 规则
type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_harness_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Rule) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Rule) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建规则请求
type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_harness_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRuleRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRuleRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CreateRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateRuleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 列出规则请求
type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_harness_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{2}
}

func (x *ListRulesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListRulesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 列出规则响应
type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_harness_harness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{3}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// 更新规则请求
type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TenantId      string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_harness_harness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRuleRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRuleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateRuleRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *UpdateRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateRuleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 删除规则请求
type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_harness_harness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRuleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 护栏检查请求
type GuardrailCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardrailCheckRequest) Reset() {
	*x = GuardrailCheckRequest{}
	mi := &file_harness_harness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardrailCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardrailCheckRequest) ProtoMessage() {}

func (x *GuardrailCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardrailCheckRequest.ProtoReflect.Descriptor instead.
func (*GuardrailCheckRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{6}
}

func (x *GuardrailCheckRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GuardrailCheckRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GuardrailCheckRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 护栏检查响应
type GuardrailCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Violations    []string               `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardrailCheckResponse) Reset() {
	*x = GuardrailCheckResponse{}
	mi := &file_harness_harness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardrailCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardrailCheckResponse) ProtoMessage() {}

func (x *GuardrailCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardrailCheckResponse.ProtoReflect.Descriptor instead.
func (*GuardrailCheckResponse) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{7}
}

func (x *GuardrailCheckResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *GuardrailCheckResponse) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

// 护栏检查结果
type GuardCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Violations    []string               `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCheckResult) Reset() {
	*x = GuardCheckResult{}
	mi := &file_harness_harness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCheckResult) ProtoMessage() {}

func (x *GuardCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCheckResult.ProtoReflect.Descriptor instead.
func (*GuardCheckResult) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{8}
}

func (x *GuardCheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *GuardCheckResult) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

// 规则检查结果
type RuleCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Violations    []string               `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleCheckResult) Reset() {
	*x = RuleCheckResult{}
	mi := &file_harness_harness_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleCheckResult) ProtoMessage() {}

func (x *RuleCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleCheckResult.ProtoReflect.Descriptor instead.
func (*RuleCheckResult) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{9}
}

func (x *RuleCheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RuleCheckResult) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

// 评估用例
type EvalCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SuiteId       string                 `protobuf:"bytes,2,opt,name=suite_id,json=suiteId,proto3" json:"suite_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Expected      string                 `protobuf:"bytes,5,opt,name=expected,proto3" json:"expected,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalCase) Reset() {
	*x = EvalCase{}
	mi := &file_harness_harness_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalCase) ProtoMessage() {}

func (x *EvalCase) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalCase.ProtoReflect.Descriptor instead.
func (*EvalCase) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{10}
}

func (x *EvalCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvalCase) GetSuiteId() string {
	if x != nil {
		return x.SuiteId
	}
	return ""
}

func (x *EvalCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvalCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *EvalCase) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *EvalCase) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 评估套件
type EvalSuite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Cases         []*EvalCase            `protobuf:"bytes,4,rep,name=cases,proto3" json:"cases,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalSuite) Reset() {
	*x = EvalSuite{}
	mi := &file_harness_harness_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalSuite) ProtoMessage() {}

func (x *EvalSuite) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalSuite.ProtoReflect.Descriptor instead.
func (*EvalSuite) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{11}
}

func (x *EvalSuite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvalSuite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvalSuite) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EvalSuite) GetCases() []*EvalCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *EvalSuite) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 创建评估套件请求
type CreateEvalSuiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Cases         []*EvalCase            `protobuf:"bytes,3,rep,name=cases,proto3" json:"cases,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEvalSuiteRequest) Reset() {
	*x = CreateEvalSuiteRequest{}
	mi := &file_harness_harness_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEvalSuiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEvalSuiteRequest) ProtoMessage() {}

func (x *CreateEvalSuiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEvalSuiteRequest.ProtoReflect.Descriptor instead.
func (*CreateEvalSuiteRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEvalSuiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEvalSuiteRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEvalSuiteRequest) GetCases() []*EvalCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *CreateEvalSuiteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 运行评估请求
type RunEvalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SuiteId         string                 `protobuf:"bytes,1,opt,name=suite_id,json=suiteId,proto3" json:"suite_id,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	CompareBaseline bool                   `protobuf:"varint,3,opt,name=compare_baseline,json=compareBaseline,proto3" json:"compare_baseline,omitempty"`
	TenantId        string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunEvalRequest) Reset() {
	*x = RunEvalRequest{}
	mi := &file_harness_harness_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvalRequest) ProtoMessage() {}

func (x *RunEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvalRequest.ProtoReflect.Descriptor instead.
func (*RunEvalRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{13}
}

func (x *RunEvalRequest) GetSuiteId() string {
	if x != nil {
		return x.SuiteId
	}
	return ""
}

func (x *RunEvalRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunEvalRequest) GetCompareBaseline() bool {
	if x != nil {
		return x.CompareBaseline
	}
	return false
}

func (x *RunEvalRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 评估指标
type EvalMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faithfulness  float64                `protobuf:"fixed64,1,opt,name=faithfulness,proto3" json:"faithfulness,omitempty"`
	Relevancy     float64                `protobuf:"fixed64,2,opt,name=relevancy,proto3" json:"relevancy,omitempty"`
	Completeness  float64                `protobuf:"fixed64,3,opt,name=completeness,proto3" json:"completeness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalMetrics) Reset() {
	*x = EvalMetrics{}
	mi := &file_harness_harness_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalMetrics) ProtoMessage() {}

func (x *EvalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalMetrics.ProtoReflect.Descriptor instead.
func (*EvalMetrics) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{14}
}

func (x *EvalMetrics) GetFaithfulness() float64 {
	if x != nil {
		return x.Faithfulness
	}
	return 0
}

func (x *EvalMetrics) GetRelevancy() float64 {
	if x != nil {
		return x.Relevancy
	}
	return 0
}

func (x *EvalMetrics) GetCompleteness() float64 {
	if x != nil {
		return x.Completeness
	}
	return 0
}

// 评估结果
type EvalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Actual        string                 `protobuf:"bytes,2,opt,name=actual,proto3" json:"actual,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Passed        bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	Metrics       *EvalMetrics           `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResult) Reset() {
	*x = EvalResult{}
	mi := &file_harness_harness_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResult) ProtoMessage() {}

func (x *EvalResult) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResult.ProtoReflect.Descriptor instead.
func (*EvalResult) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{15}
}

func (x *EvalResult) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *EvalResult) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

func (x *EvalResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EvalResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *EvalResult) GetMetrics() *EvalMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 运行评估响应
type RunEvalResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunId              string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Results            []*EvalResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	AvgScore           float64                `protobuf:"fixed64,3,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	RegressionDetected bool                   `protobuf:"varint,4,opt,name=regression_detected,json=regressionDetected,proto3" json:"regression_detected,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunEvalResponse) Reset() {
	*x = RunEvalResponse{}
	mi := &file_harness_harness_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvalResponse) ProtoMessage() {}

func (x *RunEvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvalResponse.ProtoReflect.Descriptor instead.
func (*RunEvalResponse) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{16}
}

func (x *RunEvalResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvalResponse) GetResults() []*EvalResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RunEvalResponse) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *RunEvalResponse) GetRegressionDetected() bool {
	if x != nil {
		return x.RegressionDetected
	}
	return false
}

// 获取评估结果请求
type GetEvalResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvalResultsRequest) Reset() {
	*x = GetEvalResultsRequest{}
	mi := &file_harness_harness_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvalResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvalResultsRequest) ProtoMessage() {}

func (x *GetEvalResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvalResultsRequest.ProtoReflect.Descriptor instead.
func (*GetEvalResultsRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{17}
}

func (x *GetEvalResultsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetEvalResultsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// A/B 测试
type ABTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ControlModel  string                 `protobuf:"bytes,3,opt,name=control_model,json=controlModel,proto3" json:"control_model,omitempty"`
	VariantModel  string                 `protobuf:"bytes,4,opt,name=variant_model,json=variantModel,proto3" json:"variant_model,omitempty"`
	TrafficSplit  float64                `protobuf:"fixed64,5,opt,name=traffic_split,json=trafficSplit,proto3" json:"traffic_split,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABTest) Reset() {
	*x = ABTest{}
	mi := &file_harness_harness_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABTest) ProtoMessage() {}

func (x *ABTest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABTest.ProtoReflect.Descriptor instead.
func (*ABTest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{18}
}

func (x *ABTest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ABTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ABTest) GetControlModel() string {
	if x != nil {
		return x.ControlModel
	}
	return ""
}

func (x *ABTest) GetVariantModel() string {
	if x != nil {
		return x.VariantModel
	}
	return ""
}

func (x *ABTest) GetTrafficSplit() float64 {
	if x != nil {
		return x.TrafficSplit
	}
	return 0
}

func (x *ABTest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ABTest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 创建 A/B 测试请求
type CreateABTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ControlModel  string                 `protobuf:"bytes,2,opt,name=control_model,json=controlModel,proto3" json:"control_model,omitempty"`
	VariantModel  string                 `protobuf:"bytes,3,opt,name=variant_model,json=variantModel,proto3" json:"variant_model,omitempty"`
	TrafficSplit  float64                `protobuf:"fixed64,4,opt,name=traffic_split,json=trafficSplit,proto3" json:"traffic_split,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateABTestRequest) Reset() {
	*x = CreateABTestRequest{}
	mi := &file_harness_harness_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateABTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateABTestRequest) ProtoMessage() {}

func (x *CreateABTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateABTestRequest.ProtoReflect.Descriptor instead.
func (*CreateABTestRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{19}
}

func (x *CreateABTestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateABTestRequest) GetControlModel() string {
	if x != nil {
		return x.ControlModel
	}
	return ""
}

func (x *CreateABTestRequest) GetVariantModel() string {
	if x != nil {
		return x.VariantModel
	}
	return ""
}

func (x *CreateABTestRequest) GetTrafficSplit() float64 {
	if x != nil {
		return x.TrafficSplit
	}
	return 0
}

func (x *CreateABTestRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateABTestRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 获取 A/B 测试结果请求
type GetABTestResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetABTestResultRequest) Reset() {
	*x = GetABTestResultRequest{}
	mi := &file_harness_harness_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetABTestResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetABTestResultRequest) ProtoMessage() {}

func (x *GetABTestResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetABTestResultRequest.ProtoReflect.Descriptor instead.
func (*GetABTestResultRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{20}
}

func (x *GetABTestResultRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *GetABTestResultRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// A/B 测试结果
type ABTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlScore  float64                `protobuf:"fixed64,1,opt,name=control_score,json=controlScore,proto3" json:"control_score,omitempty"`
	VariantScore  float64                `protobuf:"fixed64,2,opt,name=variant_score,json=variantScore,proto3" json:"variant_score,omitempty"`
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	PValue        float64                `protobuf:"fixed64,4,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	Significant   bool                   `protobuf:"varint,5,opt,name=significant,proto3" json:"significant,omitempty"`
	Recommended   string                 `protobuf:"bytes,6,opt,name=recommended,proto3" json:"recommended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABTestResult) Reset() {
	*x = ABTestResult{}
	mi := &file_harness_harness_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABTestResult) ProtoMessage() {}

func (x *ABTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABTestResult.ProtoReflect.Descriptor instead.
func (*ABTestResult) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{21}
}

func (x *ABTestResult) GetControlScore() float64 {
	if x != nil {
		return x.ControlScore
	}
	return 0
}

func (x *ABTestResult) GetVariantScore() float64 {
	if x != nil {
		return x.VariantScore
	}
	return 0
}

func (x *ABTestResult) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ABTestResult) GetPValue() float64 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *ABTestResult) GetSignificant() bool {
	if x != nil {
		return x.Significant
	}
	return false
}

func (x *ABTestResult) GetRecommended() string {
	if x != nil {
		return x.Recommended
	}
	return ""
}

// 提升变体请求
type PromoteVariantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteVariantRequest) Reset() {
	*x = PromoteVariantRequest{}
	mi := &file_harness_harness_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteVariantRequest) ProtoMessage() {}

func (x *PromoteVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteVariantRequest.ProtoReflect.Descriptor instead.
func (*PromoteVariantRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{22}
}

func (x *PromoteVariantRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *PromoteVariantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// SLO 定义
type SLO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,4,opt,name=target,proto3" json:"target,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLO) Reset() {
	*x = SLO{}
	mi := &file_harness_harness_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLO) ProtoMessage() {}

func (x *SLO) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLO.ProtoReflect.Descriptor instead.
func (*SLO) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{23}
}

func (x *SLO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SLO) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SLO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SLO) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *SLO) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SLO) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 创建 SLO 请求
type CreateSLORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSLORequest) Reset() {
	*x = CreateSLORequest{}
	mi := &file_harness_harness_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSLORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSLORequest) ProtoMessage() {}

func (x *CreateSLORequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSLORequest.ProtoReflect.Descriptor instead.
func (*CreateSLORequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{24}
}

func (x *CreateSLORequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSLORequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSLORequest) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *CreateSLORequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateSLORequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// SLO 状态
type SLOStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Current         float64                `protobuf:"fixed64,2,opt,name=current,proto3" json:"current,omitempty"`
	Target          float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	BudgetRemaining float64                `protobuf:"fixed64,4,opt,name=budget_remaining,json=budgetRemaining,proto3" json:"budget_remaining,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SLOStatus) Reset() {
	*x = SLOStatus{}
	mi := &file_harness_harness_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLOStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLOStatus) ProtoMessage() {}

func (x *SLOStatus) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLOStatus.ProtoReflect.Descriptor instead.
func (*SLOStatus) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{25}
}

func (x *SLOStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SLOStatus) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *SLOStatus) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *SLOStatus) GetBudgetRemaining() float64 {
	if x != nil {
		return x.BudgetRemaining
	}
	return 0
}

func (x *SLOStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取 SLO 状态请求
type GetSLOStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSLOStatusRequest) Reset() {
	*x = GetSLOStatusRequest{}
	mi := &file_harness_harness_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSLOStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSLOStatusRequest) ProtoMessage() {}

func (x *GetSLOStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSLOStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSLOStatusRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{26}
}

func (x *GetSLOStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetSLOStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 获取 SLO 状态响应
type GetSLOStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*SLOStatus           `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSLOStatusResponse) Reset() {
	*x = GetSLOStatusResponse{}
	mi := &file_harness_harness_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSLOStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSLOStatusResponse) ProtoMessage() {}

func (x *GetSLOStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSLOStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSLOStatusResponse) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{27}
}

func (x *GetSLOStatusResponse) GetStatuses() []*SLOStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// Harness 对话请求
type HarnessChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessChatRequest) Reset() {
	*x = HarnessChatRequest{}
	mi := &file_harness_harness_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessChatRequest) ProtoMessage() {}

func (x *HarnessChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessChatRequest.ProtoReflect.Descriptor instead.
func (*HarnessChatRequest) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{28}
}

func (x *HarnessChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HarnessChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HarnessChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *HarnessChatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HarnessChatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HarnessChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HarnessChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Harness 对话响应
type HarnessChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	InputGuard    *GuardCheckResult      `protobuf:"bytes,2,opt,name=input_guard,json=inputGuard,proto3" json:"input_guard,omitempty"`
	OutputGuard   *GuardCheckResult      `protobuf:"bytes,3,opt,name=output_guard,json=outputGuard,proto3" json:"output_guard,omitempty"`
	RuleCheck     *RuleCheckResult       `protobuf:"bytes,4,opt,name=rule_check,json=ruleCheck,proto3" json:"rule_check,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Tokens        int32                  `protobuf:"varint,6,opt,name=tokens,proto3" json:"tokens,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	AbTest        *ABTestInfo            `protobuf:"bytes,8,opt,name=ab_test,json=abTest,proto3" json:"ab_test,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessChatResponse) Reset() {
	*x = HarnessChatResponse{}
	mi := &file_harness_harness_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessChatResponse) ProtoMessage() {}

func (x *HarnessChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessChatResponse.ProtoReflect.Descriptor instead.
func (*HarnessChatResponse) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{29}
}

func (x *HarnessChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HarnessChatResponse) GetInputGuard() *GuardCheckResult {
	if x != nil {
		return x.InputGuard
	}
	return nil
}

func (x *HarnessChatResponse) GetOutputGuard() *GuardCheckResult {
	if x != nil {
		return x.OutputGuard
	}
	return nil
}

func (x *HarnessChatResponse) GetRuleCheck() *RuleCheckResult {
	if x != nil {
		return x.RuleCheck
	}
	return nil
}

func (x *HarnessChatResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *HarnessChatResponse) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *HarnessChatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HarnessChatResponse) GetAbTest() *ABTestInfo {
	if x != nil {
		return x.AbTest
	}
	return nil
}

func (x *HarnessChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A/B 测试信息
type ABTestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABTestInfo) Reset() {
	*x = ABTestInfo{}
	mi := &file_harness_harness_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABTestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABTestInfo) ProtoMessage() {}

func (x *ABTestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_harness_harness_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABTestInfo.ProtoReflect.Descriptor instead.
func (*ABTestInfo) Descriptor() ([]byte, []int) {
	return file_harness_harness_proto_rawDescGZIP(), []int{30}
}

func (x *ABTestInfo) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ABTestInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ABTestInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_harness_harness_proto protoreflect.FileDescriptor

const file_harness_harness_proto_rawDesc = "" +
	"\n" +
	"\x15harness/harness.proto\x12\aharness\x1a\x13common/common.proto\"\xc9\x01\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xa5\x01\n" +
	"\x11CreateRuleRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"J\n" +
	"\x10ListRulesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"8\n" +
	"\x11ListRulesResponse\x12#\n" +
	"\x05rules\x18\x01 \x03(\v2\r.harness.RuleR\x05rules\"\xb5\x01\n" +
	"\x11UpdateRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\"@\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"b\n" +
	"\x15GuardrailCheckRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"P\n" +
	"\x16GuardrailCheckResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x03(\tR\n" +
	"violations\"J\n" +
	"\x10GuardCheckResult\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x03(\tR\n" +
	"violations\"I\n" +
	"\x0fRuleCheckResult\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x03(\tR\n" +
	"violations\"\xf5\x01\n" +
	"\bEvalCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bsuite_id\x18\x02 \x01(\tR\asuiteId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x1a\n" +
	"\bexpected\x18\x05 \x01(\tR\bexpected\x12;\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1f.harness.EvalCase.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\tEvalSuite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x05cases\x18\x04 \x03(\v2\x11.harness.EvalCaseR\x05cases\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x94\x01\n" +
	"\x16CreateEvalSuiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x05cases\x18\x03 \x03(\v2\x11.harness.EvalCaseR\x05cases\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\x89\x01\n" +
	"\x0eRunEvalRequest\x12\x19\n" +
	"\bsuite_id\x18\x01 \x01(\tR\asuiteId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12)\n" +
	"\x10compare_baseline\x18\x03 \x01(\bR\x0fcompareBaseline\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"s\n" +
	"\vEvalMetrics\x12\"\n" +
	"\ffaithfulness\x18\x01 \x01(\x01R\ffaithfulness\x12\x1c\n" +
	"\trelevancy\x18\x02 \x01(\x01R\trelevancy\x12\"\n" +
	"\fcompleteness\x18\x03 \x01(\x01R\fcompleteness\"\x9b\x01\n" +
	"\n" +
	"EvalResult\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x16\n" +
	"\x06actual\x18\x02 \x01(\tR\x06actual\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12.\n" +
	"\ametrics\x18\x05 \x01(\v2\x14.harness.EvalMetricsR\ametrics\"\xa5\x01\n" +
	"\x0fRunEvalResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12-\n" +
	"\aresults\x18\x02 \x03(\v2\x13.harness.EvalResultR\aresults\x12\x1b\n" +
	"\tavg_score\x18\x03 \x01(\x01R\bavgScore\x12/\n" +
	"\x13regression_detected\x18\x04 \x01(\bR\x12regressionDetected\"K\n" +
	"\x15GetEvalResultsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xd2\x01\n" +
	"\x06ABTest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rcontrol_model\x18\x03 \x01(\tR\fcontrolModel\x12#\n" +
	"\rvariant_model\x18\x04 \x01(\tR\fvariantModel\x12#\n" +
	"\rtraffic_split\x18\x05 \x01(\x01R\ftrafficSplit\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xd0\x01\n" +
	"\x13CreateABTestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rcontrol_model\x18\x02 \x01(\tR\fcontrolModel\x12#\n" +
	"\rvariant_model\x18\x03 \x01(\tR\fvariantModel\x12#\n" +
	"\rtraffic_split\x18\x04 \x01(\x01R\ftrafficSplit\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"N\n" +
	"\x16GetABTestResultRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xcb\x01\n" +
	"\fABTestResult\x12#\n" +
	"\rcontrol_score\x18\x01 \x01(\x01R\fcontrolScore\x12#\n" +
	"\rvariant_score\x18\x02 \x01(\x01R\fvariantScore\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x17\n" +
	"\ap_value\x18\x04 \x01(\x01R\x06pValue\x12 \n" +
	"\vsignificant\x18\x05 \x01(\bR\vsignificant\x12 \n" +
	"\vrecommended\x18\x06 \x01(\tR\vrecommended\"M\n" +
	"\x15PromoteVariantRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x8f\x01\n" +
	"\x03SLO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x04 \x01(\x01R\x06target\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x8a\x01\n" +
	"\x10CreateSLORequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x01R\x06target\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"\x94\x01\n" +
	"\tSLOStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x01R\acurrent\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x01R\x06target\x12)\n" +
	"\x10budget_remaining\x18\x04 \x01(\x01R\x0fbudgetRemaining\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"M\n" +
	"\x13GetSLOStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"F\n" +
	"\x14GetSLOStatusResponse\x12.\n" +
	"\bstatuses\x18\x01 \x03(\v2\x12.harness.SLOStatusR\bstatuses\"\xd9\x01\n" +
	"\x12HarnessChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\xed\x02\n" +
	"\x13HarnessChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12:\n" +
	"\vinput_guard\x18\x02 \x01(\v2\x19.harness.GuardCheckResultR\n" +
	"inputGuard\x12<\n" +
	"\foutput_guard\x18\x03 \x01(\v2\x19.harness.GuardCheckResultR\voutputGuard\x127\n" +
	"\n" +
	"rule_check\x18\x04 \x01(\v2\x18.harness.RuleCheckResultR\truleCheck\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12\x16\n" +
	"\x06tokens\x18\x06 \x01(\x05R\x06tokens\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12,\n" +
	"\aab_test\x18\b \x01(\v2\x13.harness.ABTestInfoR\x06abTest\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"Q\n" +
	"\n" +
	"ABTestInfo\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model2\x80\b\n" +
	"\x0eHarnessService\x127\n" +
	"\n" +
	"CreateRule\x12\x1a.harness.CreateRuleRequest\x1a\r.harness.Rule\x12B\n" +
	"\tListRules\x12\x19.harness.ListRulesRequest\x1a\x1a.harness.ListRulesResponse\x127\n" +
	"\n" +
	"UpdateRule\x12\x1a.harness.UpdateRuleRequest\x1a\r.harness.Rule\x127\n" +
	"\n" +
	"DeleteRule\x12\x1a.harness.DeleteRuleRequest\x1a\r.common.Empty\x12Q\n" +
	"\x0eCheckGuardrail\x12\x1e.harness.GuardrailCheckRequest\x1a\x1f.harness.GuardrailCheckResponse\x12F\n" +
	"\x0fCreateEvalSuite\x12\x1f.harness.CreateEvalSuiteRequest\x1a\x12.harness.EvalSuite\x12<\n" +
	"\aRunEval\x12\x17.harness.RunEvalRequest\x1a\x18.harness.RunEvalResponse\x12J\n" +
	"\x0eGetEvalResults\x12\x1e.harness.GetEvalResultsRequest\x1a\x18.harness.RunEvalResponse\x12=\n" +
	"\fCreateABTest\x12\x1c.harness.CreateABTestRequest\x1a\x0f.harness.ABTest\x12I\n" +
	"\x0fGetABTestResult\x12\x1f.harness.GetABTestResultRequest\x1a\x15.harness.ABTestResult\x12?\n" +
	"\x0ePromoteVariant\x12\x1e.harness.PromoteVariantRequest\x1a\r.common.Empty\x124\n" +
	"\tCreateSLO\x12\x19.harness.CreateSLORequest\x1a\f.harness.SLO\x12K\n" +
	"\fGetSLOStatus\x12\x1c.harness.GetSLOStatusRequest\x1a\x1d.harness.GetSLOStatusResponse\x12A\n" +
	"\x04Chat\x12\x1b.harness.HarnessChatRequest\x1a\x1c.harness.HarnessChatResponse\x12I\n" +
	"\n" +
	"ChatStream\x12\x1b.harness.HarnessChatRequest\x1a\x1c.harness.HarnessChatResponse0\x01B\x1fZ\x1dagent-platform/pkg/pb/harnessb\x06proto3"

var (
	file_harness_harness_proto_rawDescOnce sync.Once
	file_harness_harness_proto_rawDescData []byte
)

func file_harness_harness_proto_rawDescGZIP() []byte {
	file_harness_harness_proto_rawDescOnce.Do(func() {
		file_harness_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_harness_proto_rawDesc), len(file_harness_harness_proto_rawDesc)))
	})
	return file_harness_harness_proto_rawDescData
}

var file_harness_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_harness_harness_proto_goTypes = []any{
	(*Rule)(nil),                   // 0: harness.Rule
	(*CreateRuleRequest)(nil),      // 1: harness.CreateRuleRequest
	(*ListRulesRequest)(nil),       // 2: harness.ListRulesRequest
	(*ListRulesResponse)(nil),      // 3: harness.ListRulesResponse
	(*UpdateRuleRequest)(nil),      // 4: harness.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),      // 5: harness.DeleteRuleRequest
	(*GuardrailCheckRequest)(nil),  // 6: harness.GuardrailCheckRequest
	(*GuardrailCheckResponse)(nil), // 7: harness.GuardrailCheckResponse
	(*GuardCheckResult)(nil),       // 8: harness.GuardCheckResult
	(*RuleCheckResult)(nil),        // 9: harness.RuleCheckResult
	(*EvalCase)(nil),               // 10: harness.EvalCase
	(*EvalSuite)(nil),              // 11: harness.EvalSuite
	(*CreateEvalSuiteRequest)(nil), // 12: harness.CreateEvalSuiteRequest
	(*RunEvalRequest)(nil),         // 13: harness.RunEvalRequest
	(*EvalMetrics)(nil),            // 14: harness.EvalMetrics
	(*EvalResult)(nil),             // 15: harness.EvalResult
	(*RunEvalResponse)(nil),        // 16: harness.RunEvalResponse
	(*GetEvalResultsRequest)(nil),  // 17: harness.GetEvalResultsRequest
	(*ABTest)(nil),                 // 18: harness.ABTest
	(*CreateABTestRequest)(nil),    // 19: harness.CreateABTestRequest
	(*GetABTestResultRequest)(nil), // 20: harness.GetABTestResultRequest
	(*ABTestResult)(nil),           // 21: harness.ABTestResult
	(*PromoteVariantRequest)(nil),  // 22: harness.PromoteVariantRequest
	(*SLO)(nil),                    // 23: harness.SLO
	(*CreateSLORequest)(nil),       // 24: harness.CreateSLORequest
	(*SLOStatus)(nil),              // 25: harness.SLOStatus
	(*GetSLOStatusRequest)(nil),    // 26: harness.GetSLOStatusRequest
	(*GetSLOStatusResponse)(nil),   // 27: harness.GetSLOStatusResponse
	(*HarnessChatRequest)(nil),     // 28: harness.HarnessChatRequest
	(*HarnessChatResponse)(nil),    // 29: harness.HarnessChatResponse
	(*ABTestInfo)(nil),             // 30: harness.ABTestInfo
	nil,                            // 31: harness.EvalCase.MetadataEntry
	(*common.Empty)(nil),           // 32: common.Empty
}
var file_harness_harness_proto_depIdxs = []int32{
	0,  // 0: harness.ListRulesResponse.rules:type_name -> harness.Rule
	31, // 1: harness.EvalCase.metadata:type_name -> harness.EvalCase.MetadataEntry
	10, // 2: harness.EvalSuite.cases:type_name -> harness.EvalCase
	10, // 3: harness.CreateEvalSuiteRequest.cases:type_name -> harness.EvalCase
	14, // 4: harness.EvalResult.metrics:type_name -> harness.EvalMetrics
	15, // 5: harness.RunEvalResponse.results:type_name -> harness.EvalResult
	25, // 6: harness.GetSLOStatusResponse.statuses:type_name -> harness.SLOStatus
	8,  // 7: harness.HarnessChatResponse.input_guard:type_name -> harness.GuardCheckResult
	8,  // 8: harness.HarnessChatResponse.output_guard:type_name -> harness.GuardCheckResult
	9,  // 9: harness.HarnessChatResponse.rule_check:type_name -> harness.RuleCheckResult
	30, // 10: harness.HarnessChatResponse.ab_test:type_name -> harness.ABTestInfo
	1,  // 11: harness.HarnessService.CreateRule:input_type -> harness.CreateRuleRequest
	2,  // 12: harness.HarnessService.ListRules:input_type -> harness.ListRulesRequest
	4,  // 13: harness.HarnessService.UpdateRule:input_type -> harness.UpdateRuleRequest
	5,  // 14: harness.HarnessService.DeleteRule:input_type -> harness.DeleteRuleRequest
	6,  // 15: harness.HarnessService.CheckGuardrail:input_type -> harness.GuardrailCheckRequest
	12, // 16: harness.HarnessService.CreateEvalSuite:input_type -> harness.CreateEvalSuiteRequest
	13, // 17: harness.HarnessService.RunEval:input_type -> harness.RunEvalRequest
	17, // 18: harness.HarnessService.GetEvalResults:input_type -> harness.GetEvalResultsRequest
	19, // 19: harness.HarnessService.CreateABTest:input_type -> harness.CreateABTestRequest
	20, // 20: harness.HarnessService.GetABTestResult:input_type -> harness.GetABTestResultRequest
	22, // 21: harness.HarnessService.PromoteVariant:input_type -> harness.PromoteVariantRequest
	24, // 22: harness.HarnessService.CreateSLO:input_type -> harness.CreateSLORequest
	26, // 23: harness.HarnessService.GetSLOStatus:input_type -> harness.GetSLOStatusRequest
	28, // 24: harness.HarnessService.Chat:input_type -> harness.HarnessChatRequest
	28, // 25: harness.HarnessService.ChatStream:input_type -> harness.HarnessChatRequest
	0,  // 26: harness.HarnessService.CreateRule:output_type -> harness.Rule
	3,  // 27: harness.HarnessService.ListRules:output_type -> harness.ListRulesResponse
	0,  // 28: harness.HarnessService.UpdateRule:output_type -> harness.Rule
	32, // 29: harness.HarnessService.DeleteRule:output_type -> common.Empty
	7,  // 30: harness.HarnessService.CheckGuardrail:output_type -> harness.GuardrailCheckResponse
	11, // 31: harness.HarnessService.CreateEvalSuite:output_type -> harness.EvalSuite
	16, // 32: harness.HarnessService.RunEval:output_type -> harness.RunEvalResponse
	16, // 33: harness.HarnessService.GetEvalResults:output_type -> harness.RunEvalResponse
	18, // 34: harness.HarnessService.CreateABTest:output_type -> harness.ABTest
	21, // 35: harness.HarnessService.GetABTestResult:output_type -> harness.ABTestResult
	32, // 36: harness.HarnessService.PromoteVariant:output_type -> common.Empty
	23, // 37: harness.HarnessService.CreateSLO:output_type -> harness.SLO
	27, // 38: harness.HarnessService.GetSLOStatus:output_type -> harness.GetSLOStatusResponse
	29, // 39: harness.HarnessService.Chat:output_type -> harness.HarnessChatResponse
	29, // 40: harness.HarnessService.ChatStream:output_type -> harness.HarnessChatResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_harness_harness_proto_init() }
func file_harness_harness_proto_init() {
	if File_harness_harness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_harness_proto_rawDesc), len(file_harness_harness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_harness_proto_goTypes,
		DependencyIndexes: file_harness_harness_proto_depIdxs,
		MessageInfos:      file_harness_harness_proto_msgTypes,
	}.Build()
	File_harness_harness_proto = out.File
	file_harness_harness_proto_goTypes = nil
	file_harness_harness_proto_depIdxs = nil
}
